export const googleFonts = [
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Oswald',
  'Source Sans Pro',
  'Slabo 27px',
  'Raleway',
  'Poppins',
  'Ubuntu',
  'Merriweather',
  'PT Sans',
  'Noto Sans',
  'Nunito Sans',
  'Playfair Display',
];

export const fontSizes = [
  '0.857rem',
  '1rem',
  '1.25rem',
  '1.5rem',
  '1.75rem',
  '2rem',
  '2.5rem',
  '3rem',
  '3.5rem',
  '4rem',
  '5rem',
];

export const spacings = [
  '8px',
  '12px',
  '16px',
  '20px',
  '24px',
  '32px',
  '40px',
  '48px',
  '56px',
  '64px',
];

export const borderRadius = ['0px', '4px', '8px', '12px', '16px', '20px'];

export const websiteConfig = [
  // Website Details
  { type: 'heading', label: 'Website Details' },
  {
    label: 'Website Name',
    description: 'The name of the website.',
    database_key: 'name',
    data_type: 'text',
  },
  // Theme
  { type: 'heading', label: 'Theme' },
  { type: 'subheading', label: 'Colors' },
  {
    label: 'Primary Color',
    description:
      'The main color used throughout the website for primary actions and highlights.',
    database_key: 'colors_primary',
    data_type: 'text',
  },
  {
    label: 'Secondary Color',
    description:
      'The secondary color used for secondary actions and highlights.',
    database_key: 'colors_secondary',
    data_type: 'text',
  },
  {
    label: 'Accent Color',
    description: 'An accent color used to draw attention to specific elements.',
    database_key: 'colors_accent',
    data_type: 'text',
  },
  {
    label: 'Light Color',
    description: 'A light shade used for backgrounds and light elements.',
    database_key: 'colors_light',
    data_type: 'text',
  },
  {
    label: 'Dark Color',
    description: 'A dark shade used for text and dark elements.',
    database_key: 'colors_dark',
    data_type: 'text',
  },
  { type: 'subheading', label: 'Font' },
  {
    label: 'Font Family',
    description: 'The primary font family used across the website.',
    database_key: 'font_primary',
    data_type: 'select',
    options: googleFonts,
  },
  { type: 'subsubheading', label: 'Sizes' },
  {
    label: 'Small Font Size',
    description: 'The size used for small text elements.',
    database_key: 'font_small',
    data_type: 'select',
    options: fontSizes,
  },
  {
    label: 'Medium Font Size',
    description: 'The default font size for body text.',
    database_key: 'font_medium',
    data_type: 'select',
    options: fontSizes,
  },
  {
    label: 'Large Font Size',
    description: 'The size used for larger text elements like subtitles.',
    database_key: 'font_large',
    data_type: 'select',
    options: fontSizes,
  },
  {
    label: 'Extra Large Font Size',
    description: 'The size used for headings.',
    database_key: 'font_xlarge',
    data_type: 'select',
    options: fontSizes,
  },
  {
    label: 'Massive Font Size',
    description: 'The size used for prominent headings or banners.',
    database_key: 'font_massive',
    data_type: 'select',
    options: fontSizes,
  },
  { type: 'subheading', label: 'Spacing' },
  {
    label: 'Small Spacing',
    description: 'The spacing used for small gaps between elements.',
    database_key: 'spacings_small',
    data_type: 'select',
    options: spacings,
  },
  {
    label: 'Medium Spacing',
    description: 'The default spacing between elements.',
    database_key: 'spacings_medium',
    data_type: 'select',
    options: spacings,
  },
  {
    label: 'Large Spacing',
    description: 'The spacing used for separating large sections.',
    database_key: 'spacings_large',
    data_type: 'select',
    options: spacings,
  },
  {
    label: 'Extra Large Spacing',
    description: 'The spacing used for extra separation between elements.',
    database_key: 'spacings_xlarge',
    data_type: 'select',
    options: spacings,
  },
  { type: 'subheading', label: 'Responsive Breakpoints' },
  {
    label: 'Mobile Breakpoint',
    description: 'The maximum width for mobile devices.',
    database_key: 'breakpoints_mobile',
    data_type: 'text',
  },
  {
    label: 'Tablet Breakpoint',
    description: 'The maximum width for tablet devices.',
    database_key: 'breakpoints_tablet',
    data_type: 'text',
  },
  {
    label: 'Desktop Breakpoint',
    description: 'The minimum width for desktop devices.',
    database_key: 'breakpoints_desktop',
    data_type: 'text',
  },
  {
    label: 'Max Width',
    description: 'The maximum width for content containers.',
    database_key: 'breakpoints_maxWidth',
    data_type: 'text',
  },
  { type: 'subheading', label: 'Other Theming Items' },
  {
    label: 'Border Radius',
    description: 'The radius applied to rounded corners.',
    database_key: 'borders_radius',
    data_type: 'select',
    options: borderRadius,
  },
  {
    label: 'Nav Logo Width',
    description: 'The width of the logo in the navigation bar.',
    database_key: 'nav_logo',
    data_type: 'text',
  },
  {
    label: 'On Hover Opacity',
    description: 'The opacity level when hovering over interactive elements.',
    database_key: 'hover_opacity',
    data_type: 'text',
  },
  // Header Information
  { type: 'heading', label: 'Header Information' },
  {
    label: 'Title',
    description: 'The title of your website shown in the browser tab.',
    database_key: 'header_title',
    data_type: 'text',
  },
  {
    label: 'Description',
    description: 'A brief description of your website for SEO purposes.',
    database_key: 'header_description',
    data_type: 'textarea',
  },
  {
    label: 'Keywords',
    description: 'Keywords relevant to your website for SEO.',
    database_key: 'header_keywords',
    data_type: 'textarea',
  },
  {
    label: 'OG Title',
    description: 'The title used when your website is shared on social media.',
    database_key: 'header_ogtitle',
    data_type: 'text',
  },
  {
    label: 'OG Type',
    description:
      'The type of content (e.g., website, article) for Open Graph meta tags.',
    database_key: 'header_ogtype',
    data_type: 'text',
  },
  {
    label: 'OG URL',
    description: 'The canonical URL of your website for Open Graph meta tags.',
    database_key: 'header_ogurl',
    data_type: 'text',
  },
  {
    label: 'OG Image',
    description:
      'An image URL used when your website is shared on social media.',
    database_key: 'header_ogimage',
    data_type: 'text',
  },
  {
    label: 'Theme Color',
    description: 'The theme color for browsers and devices that support it.',
    database_key: 'header_themecolor',
    data_type: 'text',
  },
  // Business Information
  { type: 'heading', label: 'Business Information' },
  {
    label: 'Legal Name',
    description: 'The legal name of your business.',
    database_key: 'business_name',
    data_type: 'text',
  },
  {
    label: 'Registered Address',
    description: 'The official registered address of your business.',
    database_key: 'business_address',
    data_type: 'textarea',
  },
  {
    label: 'Phone',
    description: 'The primary contact phone number for your business.',
    database_key: 'business_phone',
    data_type: 'tel',
  },
  {
    label: 'Email',
    description: 'The primary contact email address for your business.',
    database_key: 'business_email',
    data_type: 'email',
  },
  {
    label: 'FCA Number',
    description: 'Your Financial Conduct Authority registration number.',
    database_key: 'business_fca_number',
    data_type: 'text',
  },
  {
    label: 'Registered Company Number',
    description: 'Your company registration number.',
    database_key: 'business_company_number',
    data_type: 'text',
  },
  // Social Media Links
  { type: 'heading', label: 'Social Media Links' },
  {
    label: 'LinkedIn URL',
    description: 'The URL of your LinkedIn profile or company page.',
    database_key: 'linkedin_url',
    data_type: 'text',
  },
  {
    label: 'Twitter (X) URL',
    description: 'The URL of your Twitter profile.',
    database_key: 'x_twitter_url',
    data_type: 'text',
  },
  {
    label: 'Facebook URL',
    description: 'The URL of your Facebook page.',
    database_key: 'facebook_url',
    data_type: 'text',
  },
  {
    label: 'Instagram URL',
    description: 'The URL of your Instagram profile.',
    database_key: 'instagram_url',
    data_type: 'text',
  },
  {
    label: 'YouTube URL',
    description: 'The URL of your YouTube channel.',
    database_key: 'youtube_url',
    data_type: 'text',
  },
  {
    label: 'TikTok URL',
    description: 'The URL of your TikTok profile.',
    database_key: 'tiktok_url',
    data_type: 'text',
  },
];
